CREATE TABLE `API_endpoints` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `interface` VARCHAR(64) NOT NULL COMMENT 'Interface name',
  `endpoint` VARCHAR(64) NOT NULL COMMENT 'Endpoint name',
  `version` SMALLINT(255) NOT NULL DEFAULT 1 COMMENT 'Version of the endpoint',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Index of different REST API endpoints. Automatically generated by PHP when a new endpoint is called.';

ALTER TABLE `API_endpoints` 
  ADD UNIQUE INDEX `unique`(interface, endpoint, version);