CREATE TABLE `itemNameTranslations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `itemid` INT(11) UNSIGNED NOT NULL COMMENT '->items.id',
  `langID` INT(6) UNSIGNED NOT NULL COMMENT '->lang_languages.id',
  `name` VARCHAR(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '' COMMENT 'Translated item name',
  PRIMARY KEY (id, itemid, langID)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Translated Steam item names. Generated by reverse engineering how item names are built for different languages, and then build them from game file translation files.';

ALTER TABLE `itemNameTranslations` 
  ADD UNIQUE INDEX uniq(itemid, langID);

ALTER TABLE `itemNameTranslations` 
  ADD CONSTRAINT `itemTranslations_ItemId` FOREIGN KEY (itemid)
    REFERENCES items(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `itemNameTranslations` 
  ADD CONSTRAINT `itemTranslations_langId` FOREIGN KEY (langID)
    REFERENCES lang_languages(id) ON DELETE CASCADE ON UPDATE CASCADE;