CREATE TABLE `preferences` (
  `id` INT(11) NOT NULL DEFAULT 1,
  `tradesdisabled` TINYINT(4) NOT NULL DEFAULT 0 COMMENT 'Flag whether the website is under maintenance. The website is still operating, but any transfers of items have been disabled.',
  `tradeBotDisabled` TINYINT(255) NOT NULL DEFAULT 0 COMMENT 'Flag whether trades on the tradebot are disabled. A maintenance message is shown.',
  `screenshotsDisabled` TINYINT(4) NOT NULL DEFAULT 0 COMMENT 'Flag whether the screenshot tool is disabled',
  `steamTradesDisabled` TINYINT(255) NOT NULL DEFAULT 0 COMMENT 'Flag set if steam trades are unreliable, disables Steam trading',
  `fInventoryUpdaterSetUpdate` TINYINT(4) NOT NULL DEFAULT 0 COMMENT 'Flag set if we receive new CS2 items that should be inspected',
  `moneySafetyBalance` DECIMAL(14, 4) NOT NULL DEFAULT 0.0000 COMMENT 'Obsolete, still referred to in code. Old ZEN system-Any real money paid to users or received from them will be reflected to this value. If this value goes too low, we will disable the website.',
  `moneySafetyBalanceLimit` DECIMAL(14, 0) NOT NULL DEFAULT 0 COMMENT 'Obsolete, still referred to in code. Old ZEN system-If the total of all safety balance in USD goes below this, apply maintenance',
  `moneySafetyBalanceEuro` DECIMAL(14, 4) NOT NULL DEFAULT 0.0000 COMMENT 'Obsolete, still referred to in code. Old ZEN system-When we suppose that we received euro (like with deposits with no absolute certainty), we will add to this, when we pay users euros, we will subtract from this',
  `potentialBitcoinBalanceUSD` DECIMAL(14, 4) NOT NULL DEFAULT 0.0000 COMMENT 'Obsolete, still referred to in code. old Bitcoin system - A cron runs to update our actual Bitcoin balance from the exchange and wallet and multiplies it by the current rate',
  `potentialBitcoinBalanceLastUpdate` INT(255) NOT NULL DEFAULT 0 COMMENT 'Obsolete, still referred to in code. old Bitcoin system - ',
  `potentialBitcoinBalanceUSD_New` DECIMAL(14, 2) NOT NULL DEFAULT 0.00 COMMENT 'Our system''s Bitcoin balance in USD after transactions have been confirmed',
  `potentialBitcoinBalanceLastUpdate_New` INT(11) NOT NULL DEFAULT 0 COMMENT 'Unix timestamp when above was updated last time',
  `coldWalletBitcoinBalance` DECIMAL(13, 8) NOT NULL DEFAULT 0.00000000 COMMENT 'Amount of BTC in our cold wallet. Used for calculation to potentialBitcoinBalanceUSD_New to add on top of programmatically calculated hot wallet balance ',
  `totalWalletBitcoinBalance` DECIMAL(13, 8) NOT NULL DEFAULT 0.00000000 COMMENT 'BTC in our hot wallet. Updated by BitcoinBalanceManager',
  `BTCsatoshiPerByteFee` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'The current satoshi per byte we should use for outgoing transactions. Updated by a cron script',
  `BTCWalletXPrivKey_New` VARCHAR(255) DEFAULT NULL COMMENT 'xPriv key of our main hot wallet. Used for new users BTC wallet service where BTC is stored for users separately from Adyen balances',
  `withdrawalBitcoinFeePercent` DECIMAL(5, 4) UNSIGNED NOT NULL DEFAULT 0.0000 COMMENT 'Bitcoin cashout fee charged from users by us. e.g. 0.02 for 2%',
  `withdrawalBitcoinFeeBTC` DECIMAL(9, 8) DEFAULT 0.00010000 COMMENT 'A static fee cashout fee in BTC added on top of the fee percent.',
  `BTCInvalidUTXOValueSatoshi` INT(255) UNSIGNED DEFAULT 0 COMMENT 'Amount in satoshi that should be deducted from the wallet balance indicated by Bitcore. Used when Bitcore calculates the balance incorrectly.',
  `BTCdisabled` TINYINT(255) NOT NULL DEFAULT 0 COMMENT 'Flag whether Bitcoin withdrawals and deposits are disabled. Automatically set if there are technical issues with our Bitcoin infra',
  `BTCcashoutDisabled` TINYINT(255) DEFAULT 0 COMMENT 'Flag whether Bitcoin withdrawals are disabled',
  `adyenFXDisabled` TINYINT(255) DEFAULT 1 COMMENT 'Flag whether Adyen FX is disabled. When set, FX cannot be done on marketplace orders, for example when the seller is to be paid USD and the shopper is paying with EUR',
  `adyenWalletPurchasesDisabled` TINYINT(255) NOT NULL DEFAULT 0 COMMENT 'Flag whether marketplace purchases using the user''s wallet balance is disabled. This is enabled when there is any automatically or manually detected issue with wallet payments/transfers',
  `adyenUserCryptoToCompanyFiatDisabled` TINYINT(255) NOT NULL COMMENT 'This is enabled when the company can''t pay to sellers with fiat while receiving crypto',
  `adyenUserFiatToCompanyCryptoDisabled` TINYINT(255) NOT NULL DEFAULT 0 COMMENT 'This is enabled when the company can''t pay to sellers with crypto while receiving fiat from buyer',
  `adyenAutopurchaseBalanceEUR` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'Caches the EUR balance of the Autopurchase BalanceAccount.',
  `adyenAutopurchaseBalanceUSD` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'Caches the USD balance of the Autopurchase BalanceAccount.',
  `isCryptoFeaturesHidden` TINYINT(255) NOT NULL DEFAULT 0 COMMENT 'Hide listing of items for crypto and that price is in crypto and crypto balance',
  `withdrawalAdyenBanktransferFeeStaticEUR` DECIMAL(5, 2) DEFAULT 0.30 COMMENT 'Cashout fee charged by us from users for Adyen cashouts in EUR',
  `withdrawalAdyenBanktransferFeePercent` DECIMAL(5, 4) DEFAULT 0.0150 COMMENT 'Cashout fee charged by us from users for Adyen cashouts in percent. e.g. 0.02 for 2%. Added on top of withdrawalAdyenBanktransferFeeStaticEUR',
  `globalAnnouncementHTML` TEXT DEFAULT NULL COMMENT 'If set, displays an announcement on all web pages with this HTML content',
  `globalAnnouncementClass` VARCHAR(24) DEFAULT NULL COMMENT 'List of classes to be used for the HTML element for the announcement',
  `featuredTwitterGiveawayTweetId` VARCHAR(64) DEFAULT NULL COMMENT 'Set when there is an ongoing giveaway by us on Twitter. Set to the Tweet''s id. The tweet is embedded and promoted on the website.',
  `globalTradeBotReviewEndTime` INT(10) UNSIGNED DEFAULT 0 COMMENT 'Used when prices are updated and we want to set all items in review time',
  `cloudflareAPIKey` VARCHAR(64) DEFAULT NULL COMMENT 'Our Cloudflare API key',
  `tradeTokenPurchaseBonus` DECIMAL(3, 2) DEFAULT 0.30 COMMENT 'How much more trade-tokens user well get per USD percent (e.g. 0.40)',
  `csmoneyToOurSCMRatio` FLOAT(255, 5) DEFAULT 1.00000 COMMENT 'obsolete. Average item price ratio between CSMoney''s item price and our calculated item price',
  `lootfarmSteamToOurSCMRatio` FLOAT(255, 5) DEFAULT 1.00000 COMMENT 'Average item price ratio between lootfarm''s Steam item price and our calculated item price',
  `lootfarmPriceToOurSCMRatio` FLOAT(255, 5) DEFAULT 1.00000 COMMENT 'Average item price ratio between lootfarm''s item price and our calculated item price',
  `p2pC5TradesDisabled` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_unicode_ci,
COMMENT = 'Table for dynamic website and system preferences and settings and for persisting frequently updating numbers, such as system Bitcoin balance';