CREATE TABLE `statTracking` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `tradedIn` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'Value of items traded in in our local price',
  `tradedOut` DECIMAL(10, 2) NOT NULL COMMENT 'Value of items traded out in our local price',
  `tmpField` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `tradeBalanceIn` DECIMAL(10, 2) NOT NULL COMMENT 'Trade bot balance that was traded to the bot',
  `tradeBalanceOut` DECIMAL(10, 2) NOT NULL COMMENT 'Trade bot balance that was paid to the users',
  `tradeBalanceToSellers` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'negative, how much was paid to usersale selelrs',
  `tradeBotTradeStatsJSON` LONGTEXT BINARY CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `skinsTradedIn` INT(11) NOT NULL DEFAULT 0 COMMENT 'Quantity of skins traded in',
  `skinsTradedOut` INT(11) NOT NULL DEFAULT 0 COMMENT 'Quantity of skins traded out',
  `keysTradedIn` INT(11) NOT NULL DEFAULT 0,
  `keysTradedOut` INT(11) NOT NULL DEFAULT 0,
  `tradesCompleted` INT(11) NOT NULL COMMENT 'Quantity of completed Steam trades',
  `tradesLogged` INT(11) NOT NULL COMMENT 'Quantity of queued/attempted Steam trades',
  `tradeSendsFailed` INT(11) NOT NULL DEFAULT 0,
  `calculatedProfitTradeBot` DECIMAL(10, 2) NOT NULL COMMENT 'Profit from the tradebot',
  `userCount` INT(11) NOT NULL COMMENT 'Number of registered users',
  `newUsers` INT(11) NOT NULL COMMENT 'Amount of new registrations',
  `inventoryValue` DECIMAL(10, 2) NOT NULL COMMENT 'Total value of items on our bots in our local price',
  `inventoryValueOld` DECIMAL(10, 2) DEFAULT NULL,
  `itemCount` INT(11) NOT NULL DEFAULT 0 COMMENT 'Total quantity of items in our bots',
  `uniqueItemCount` INT(11) NOT NULL DEFAULT 0 COMMENT 'Total quantity of unique items',
  `itemPriceAverage` DECIMAL(6, 2) NOT NULL DEFAULT 0.00,
  `itemPriceMedian` DECIMAL(6, 2) NOT NULL DEFAULT 0.00,
  `averageItemTradeTime` INT(11) NOT NULL DEFAULT 0,
  `medianItemTradeTime` INT(11) DEFAULT NULL,
  `updateTime` INT(11) NOT NULL COMMENT 'when this row was updated',
  `inventoryValueTradeBot` DECIMAL(10, 2) DEFAULT NULL,
  `itemCountTradeBot` INT(255) DEFAULT NULL,
  `uniqueItemCountTradeBot` INT(255) DEFAULT NULL,
  `itemPriceAverageTradeBot` DECIMAL(6, 2) DEFAULT NULL,
  `itemPriceMedianTradeBot` DECIMAL(6, 2) DEFAULT NULL,
  `lostProfitOnTradeBotItemPriceChange` DECIMAL(7, 2) DEFAULT NULL,
  `realMoneySales` DECIMAL(12, 4) DEFAULT 0.0000,
  `realMoneySalesFeeProfit` DECIMAL(12, 4) DEFAULT 0.0000,
  `cashoutFeeProfit` DECIMAL(12, 4) DEFAULT 0.0000,
  `cashoutFeeCosts` DECIMAL(12, 4) DEFAULT 0.0000,
  `chargebackCosts` DECIMAL(12, 2) DEFAULT NULL COMMENT 'this is positive when we lose money',
  PRIMARY KEY (id, date)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Table for consolidating business performance data daily';

ALTER TABLE `statTracking` 
  ADD UNIQUE INDEX uniq(date);