CREATE TABLE `tblAdyenBalanceReport` (
  `BalancePlatform` VARCHAR(50) DEFAULT NULL,
  `AccountHolder` VARCHAR(50) DEFAULT NULL,
  `BalanceAccount` VARCHAR(50) DEFAULT NULL,
  `Transfer Id` VARCHAR(50) DEFAULT NULL,
  `Transaction Id` VARCHAR(50) DEFAULT NULL,
  `Category` VARCHAR(50) DEFAULT NULL,
  `Status` VARCHAR(50) DEFAULT NULL,
  `Type` VARCHAR(50) DEFAULT NULL,
  `Booking Date` DATETIME DEFAULT NULL,
  `Booking Date TimeZone` VARCHAR(50) DEFAULT NULL,
  `Value Date` VARCHAR(50) DEFAULT NULL,
  `Value Date TimeZone` VARCHAR(50) DEFAULT NULL,
  `Currency` VARCHAR(50) DEFAULT NULL,
  `Amount` DOUBLE(10, 3) DEFAULT NULL,
  `Original Currency` VARCHAR(50) DEFAULT NULL,
  `Original Amount` VARCHAR(50) DEFAULT NULL,
  `Payment Currency` VARCHAR(50) DEFAULT NULL,
  `Received (PC)` DOUBLE(10, 3) DEFAULT NULL,
  `Reserved (PC)` DOUBLE(10, 3) DEFAULT NULL,
  `Balance (PC)` DOUBLE(10, 3) DEFAULT NULL,
  `Reference` VARCHAR(100) DEFAULT NULL,
  `Description` TEXT DEFAULT NULL,
  `Counterparty Balance Account Id` VARCHAR(50) DEFAULT NULL,
  `Psp Payment Merchant Reference` VARCHAR(100) DEFAULT NULL,
  `Psp Payment Psp Reference` VARCHAR(50) DEFAULT NULL,
  `Psp Modification Psp Reference` VARCHAR(50) DEFAULT NULL,
  `Psp Modification Merchant Reference` VARCHAR(100) DEFAULT NULL,
  `Payment Instrument Type` VARCHAR(50) DEFAULT NULL,
  `Payment Instrument Id` VARCHAR(50) DEFAULT NULL,
  `Entrymode` VARCHAR(50) DEFAULT NULL,
  `Auth Code` VARCHAR(50) DEFAULT NULL,
  `Shopper Interaction` VARCHAR(50) DEFAULT NULL,
  `MCC` VARCHAR(50) DEFAULT NULL,
  `Counterparty Name` VARCHAR(50) DEFAULT NULL,
  `Counterparty Address` VARCHAR(50) DEFAULT NULL,
  `Counterparty City` VARCHAR(50) DEFAULT NULL,
  `Counterparty Country` VARCHAR(50) DEFAULT NULL,
  `Counterparty iban` VARCHAR(50) DEFAULT NULL,
  `Counterparty bic` VARCHAR(50) DEFAULT NULL,
  `Counterparty Account Number` VARCHAR(50) DEFAULT NULL,
  `Counterparty Postal Code` VARCHAR(50) DEFAULT NULL,
  `Interchange Currency` VARCHAR(50) DEFAULT NULL,
  `Interchange` VARCHAR(50) DEFAULT NULL,
  `Beneficiary Balance Account` VARCHAR(50) DEFAULT NULL,
  `Brand Variant` VARCHAR(100) DEFAULT NULL,
  `Reference for Beneficiary` TEXT DEFAULT NULL,
  `Platform Payment Interchange` VARCHAR(50) DEFAULT NULL,
  `Platform Payment Scheme Fee` VARCHAR(50) DEFAULT NULL,
  `Platform Payment Markup` VARCHAR(50) DEFAULT NULL,
  `Platform Payment Commission` VARCHAR(50) DEFAULT NULL,
  `Platform Payment Cost Currency` VARCHAR(50) DEFAULT NULL,
  `Account Holder Description` VARCHAR(50) DEFAULT NULL,
  `Account Holder Reference` VARCHAR(50) DEFAULT NULL,
  `Balance Account Description` VARCHAR(50) DEFAULT NULL,
  `Balance Account Reference` VARCHAR(50) DEFAULT NULL,
  `Platform Payment Installments` VARCHAR(50) DEFAULT NULL,
  `Payment Instrument Reference` VARCHAR(50) DEFAULT NULL,
  `Payment Instrument Description` VARCHAR(50) DEFAULT NULL,
  `Issued Card Scheme Fee` VARCHAR(50) DEFAULT NULL,
  `Issued Card Scheme Fee Currency` VARCHAR(50) DEFAULT NULL,
  `Event Id` VARCHAR(50) DEFAULT NULL,
  `Reserved1` VARCHAR(50) DEFAULT NULL,
  `Reserved2` VARCHAR(50) DEFAULT NULL,
  `Reserved3` VARCHAR(50) DEFAULT NULL,
  `Reserved4` VARCHAR(50) DEFAULT NULL,
  `Reserved5` VARCHAR(50) DEFAULT NULL,
  `Reserved6` VARCHAR(50) DEFAULT NULL,
  `Reserved7` VARCHAR(50) DEFAULT NULL,
  `Reserved8` VARCHAR(50) DEFAULT NULL,
  `Reserved9` VARCHAR(50) DEFAULT NULL,
  `Reserved10` VARCHAR(50) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;