CREATE TABLE `tblImage` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `mime_type` VARCHAR(255) DEFAULT NULL,
  `content` MEDIUMBLOB DEFAULT NULL,
  `url_path` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;