CREATE TABLE `tblMarketPlaceSearchHistory` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(50) DEFAULT NULL,
  `timestamp` DATETIME DEFAULT NULL,
  `name` VARCHAR(100) DEFAULT NULL,
  `min_price` VARCHAR(50) DEFAULT NULL,
  `max_price` VARCHAR(50) DEFAULT NULL,
  `appid` INT(11) DEFAULT NULL,
  `tradable_after_seconds` INT(11) DEFAULT NULL,
  `user` VARCHAR(255) DEFAULT NULL,
  `item_type` VARCHAR(50) DEFAULT NULL,
  `owner_user_uuid` VARCHAR(50) DEFAULT NULL,
  `owner_user_id` VARCHAR(255) DEFAULT NULL,
  `bot_id` VARCHAR(255) DEFAULT NULL,
  `item_id` VARCHAR(255) DEFAULT NULL,
  `cs_stickers` VARCHAR(255) DEFAULT NULL,
  `cs_phase` VARCHAR(255) DEFAULT NULL,
  `cs_stattrak` INT(11) DEFAULT NULL,
  `cs_weapon` VARCHAR(50) DEFAULT NULL,
  `cs_min_paintwear` VARCHAR(255) DEFAULT NULL,
  `cs_max_paintwear` VARCHAR(255) DEFAULT NULL,
  `cs_exterior` VARCHAR(50) DEFAULT NULL,
  `d2_slot` VARCHAR(255) DEFAULT NULL,
  `d2_hero` VARCHAR(255) DEFAULT NULL,
  `d2_rarity` VARCHAR(255) DEFAULT NULL,
  `result_db` LONGTEXT BINARY CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`result_db`)),
  `result_os` LONGTEXT BINARY CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`result_os`)),
  `os_duration` INT(11) DEFAULT NULL,
  `db_duration` INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;