CREATE TABLE `tblOverview` (
  `date_time` VARCHAR(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `update_time` DATETIME DEFAULT current_timestamp(),
  `balance_users_account_virtutrade` DECIMAL(14, 4) DEFAULT NULL,
  `balance_users_account_crypto_usd` DECIMAL(14, 4) DEFAULT NULL,
  `balance_users_account_crypto_opening_usd` DECIMAL(14, 4) DEFAULT NULL,
  `balance_users_account_crypto_closing_usd` DECIMAL(14, 4) DEFAULT NULL,
  `users_transactions_usd` DECIMAL(14, 4) DEFAULT NULL,
  `balance_users_account_eur` DECIMAL(14, 4) DEFAULT NULL,
  `balance_users_account_usd` DECIMAL(14, 4) DEFAULT NULL,
  `balance_users_account_tokens` DECIMAL(14, 4) DEFAULT NULL,
  `btc_deposits_usd` DECIMAL(14, 4) DEFAULT NULL,
  `btc_cashouts_usd` DECIMAL(14, 4) DEFAULT NULL,
  `fiat_deposits_usd` DECIMAL(14, 4) DEFAULT NULL,
  `fiat_cashouts_usd` DECIMAL(14, 4) DEFAULT NULL,
  `sales_usd` DECIMAL(14, 4) DEFAULT NULL,
  `sales_instant_usd` DECIMAL(14, 4) DEFAULT NULL,
  `sales_p2p_usd` DECIMAL(14, 4) DEFAULT 0.0000,
  `company_btc_wallet` DECIMAL(14, 8) DEFAULT NULL,
  `company_btc_wallet_usd` DECIMAL(14, 4) DEFAULT NULL,
  `instant_sale_provider_balance_usd` DECIMAL(14, 4) DEFAULT NULL,
  `instant_sale_provider_deals_usd` DECIMAL(14, 4) DEFAULT NULL,
  `instant_sale_provider_withdraws_usd` DECIMAL(14, 4) DEFAULT NULL,
  `inventory_value_usd` DECIMAL(39, 6) DEFAULT NULL,
  `cryptocom_balance_usdt` DECIMAL(14, 4) DEFAULT NULL,
  `revolut_balance_usd` DECIMAL(14, 4) DEFAULT NULL,
  `revolut_balance_eur` DECIMAL(14, 4) DEFAULT NULL,
  `fiat_balance_usd` DECIMAL(14, 4) DEFAULT NULL,
  `fiat_balance_eur` DECIMAL(14, 4) DEFAULT NULL,
  `profit_sales_usd` DECIMAL(14, 4) DEFAULT 0.0000,
  `profit_sales_instant_usd` DECIMAL(14, 4) DEFAULT NULL,
  `profit_sales_p2p_usd` DECIMAL(14, 4) DEFAULT NULL,
  `profit_deposit_btc_usd` DECIMAL(14, 4) DEFAULT NULL,
  `profit_deposit_fiat_usd` DECIMAL(14, 4) DEFAULT NULL,
  `profit_cashout_btc_usd` DECIMAL(14, 4) DEFAULT NULL,
  `profit_cashout_fiat_usd` DECIMAL(14, 4) DEFAULT NULL,
  `net_profit` DECIMAL(14, 4) GENERATED ALWAYS AS (ifnull(`profit_sales_usd`,0) + ifnull(`profit_sales_instant_usd`,0) + ifnull(`profit_sales_p2p_usd`,0) + ifnull(`profit_cashout_btc_usd`,0)) STORED,
  PRIMARY KEY (date_time)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;