CREATE TABLE `userSales_Marketplace_SubCategories` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoryId` INT(11) UNSIGNED NOT NULL COMMENT '->userSales_Marketplace_MainCategories.id',
  `text` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'shown to the user',
  `filterColumn` VARCHAR(255) DEFAULT NULL COMMENT 'this is the name of the column which is passed to the GET request. Filters are grouped by this',
  PRIMARY KEY (id, categoryId),
  INDEX id(id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Steam item sub categories under main categories. Contents are automatically generated by a cron script from the items available on the marketplace.';

ALTER TABLE `userSales_Marketplace_SubCategories` 
  ADD UNIQUE INDEX uniq(categoryId, text, filterColumn);

ALTER TABLE `userSales_Marketplace_SubCategories` 
  ADD CONSTRAINT `userSales_Marketplace_SubCategories_categoryId` FOREIGN KEY (categoryId)
    REFERENCES userSales_Marketplace_MainCategories(categoryId) ON DELETE CASCADE ON UPDATE CASCADE;