CREATE TABLE `userSales_Marketplace_MainCategories` (
  `categoryId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'used for main categories',
  `appid` MEDIUMINT(8) UNSIGNED NOT NULL,
  `text` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'shown to the user',
  `filterColumn` VARCHAR(255) NOT NULL COMMENT 'this is the name of the column which is passed to the GET request. Filters are grouped by this',
  PRIMARY KEY (categoryId)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci,
COMMENT = 'Steam item categories. Contents are automatically generated by a cron script from the items available on the marketplace.';

ALTER TABLE `userSales_Marketplace_MainCategories` 
  ADD UNIQUE INDEX uniq(appid, text, filterColumn);